#!/bin/bash
if [ -z "$1" ]; then
    echo "Usage: $0 <vpnname|ip>"
    exit 1
fi

if [[ $1 == "localhost" ]]; then # hardcoded
    exit 0
fi

if [[ ! $(timeout --version 2>/dev/null; echo $?) -eq 0 ]]; then
    function timeout() { perl -e 'alarm shift; exec @ARGV' "$@"; }
fi
 
ip_regex="([0-9]{1,3}\.){3}[0-9]{1,3}"
if [[ $1 =~ $ip_regex ]]; then
    if [ ! -z "$(timeout 0.1 nc -vz $1 22 2>&1 | grep "succeeded")" ]; then # todo: port should be configurable
        exit 0
    else
        exit 1 # exit as a VPN unlikely has an IP as name
    fi
fi

hostname_regex="([a-zA-Z0-9]+\.){1,}[a-zA-Z0-9]+"
if [[ $1 =~ $hostname_regex ]]; then
    if [ ! -z "$(timeout 0.1 nc -z $1 22 2>&1 | grep "succeeded")" ]; then # todo: port should be configurable
        exit 0
    fi
    # dont't exit, because a VPN name could look like a hostname
fi

# if darwin
if [ "$(uname)" == "Darwin" ]; then
    if [ -z "$(scutil --nc list nor | grep "Connected" | cut -d\" -f2 | grep $1)" ]; then
        exit 1
    else
        exit 0
    fi
# if linux
elif [ "$(uname)" == "Linux" ]; then
    if [ -z "$(nmcli connection show --active | grep $1)" ]; then
        exit 1
    else
        exit 0
    fi
fi

exit 1
